name: Code Quality Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install pdm
      run: |
        pip install pdm

    - name: Install dev dependencies
      run: |
        pdm install --group: dev

    - name: Run code linting
      run: |
        make lint

    - name: Run code format
      run: |
        make format

    - name: Run type check
      run: |
        make typecheck
