name: Test and coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pdm
        run: |
          pip install pdm

      - name: Install coverage
        run: |
          pip install coverage

      - name: Install dependencies
        run: |
          pdm install --group :all

      - name: Test with pytest
        run: |
          coverage run -m pytest  -v -s

      - name: Generate Coverage Report
        run: |
          coverage report -m
