name: Test and coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pdm
        run: |
          pip install pdm

      - name: Install dependencies
        run: |
          pdm install --group test

      - name: Run tests with pytest
        run: |
          make test
          pip install coverage
          coverage report
          coverage html

      - name: Archive code coverage html report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: src/htmlcov
